### ISSUE TITLE
Commit

### ISSUE THREAD

**Issue by ewiedermann** [PlusCel/PlusCel#1]
Hola nacho, fíjate que los commit son atómicos. Es el cambio mas chico un commit.
Fíjate los commit como los hicimos en mi grupo
https://github.com/ProyectoTypes/inventariohardware

**Comment by chernobyl** [comment]
Gracias por el aporte Exequiel, lo estamos hablando con los chicos para
mejorar la forma de trabajo en github.

saludos

NAcho.-

2015-06-03 11:19 GMT-03:00 ExequielNeuquen notifications@github.com:
